# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-19 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formModel',
            fields=[
                ('identifiant', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Date_vol', models.DateField()),
                ('Numero_vol', models.CharField(max_length=7)),
                ('Numero_siege', models.CharField(max_length=50)),
                ('Venant_de', models.CharField(max_length=50)),
                ('Allant_a', models.CharField(max_length=50)),
                ('Numero_passport', models.CharField(max_length=50)),
                ('Date_delivrance_passport', models.DateField()),
                ('Passport_emis_par', models.CharField(max_length=50)),
                ('Delivre_par', models.CharField(max_length=50)),
                ('Date_expiration', models.DateField()),
                ('Num_visa', models.CharField(default=b'N/C', max_length=50)),
                ('Visa_delivre_par', models.CharField(default=b'N/C', max_length=20)),
                ('Duree_validite', models.CharField(default=b'N/C', max_length=20)),
                ('Nom_famille', models.CharField(max_length=50)),
                ('Prenom', models.CharField(max_length=50)),
                ('Date_naissance', models.DateField()),
                ('Lieu_naissance', models.CharField(max_length=50)),
                ('Genre', models.CharField(choices=[(b'Homme', b'Homme'), (b'Femme', b'Femme')], max_length=50)),
                ('Nationalite', models.CharField(max_length=50)),
                ('Profession', models.CharField(max_length=50)),
                ('Telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('Email', models.CharField(max_length=50)),
                ('Adresse_locale', models.CharField(max_length=50)),
                ('Adresse_Etranger', models.CharField(max_length=50)),
            ],
        ),
    ]
