# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-19 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mali_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formmodel',
            name='Delivre_par',
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='Telephone',
            field=models.CharField(max_length=13),
        ),
    ]
