# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-19 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mali_project', '0002_auto_20171119_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmodel',
            name='Date_expiration',
            field=models.CharField(max_length=50),
        ),
    ]
